### ISSUE TITLE
`org-mru-clock-select-recent` doesn't select `d`, `i`, or `c`

### ISSUE THREAD

**Issue by stites** [unhammer/org-mru-clock#13]
Using doom-emacs and creating the mru cache from org-agendas, whenever I trigger `org-mru-clock-select-recent` and select one of the default, interrupted, or current tasks I am sent to a different item in my org-journal folder (which is referenced at the bottom of my `org-agenda-files`).

**Comment by unhammer** [comment]
There's a bug in org-mode where it re-uses those letters (any long enough clock history would hit this bug). Added a workaround to call that function with a truncated history (sometimes dynamic binding is nice to have)
