### ISSUE TITLE
Bad Bounding indices 0，43

### ISSUE THREAD

**Issue by jueqingsizhe66** [unhammer/org-mru-clock#14]
**Debugger entered--Lisp error: (error "Bad bounding indices: 0, 43")**
signal(error ("Bad bounding indices: 0, 43"))
error("%s" "Bad bounding indices: 0, 43")
cl-subseq((#<marker (moves after insertion) at 73765 in newgtd.org> #<marker (moves after insertion) at 61780 in newgtd.org> #<marker (moves after insertion) at 159358 in newgtd.org> #<marker (moves after insertion) at 160657 in newgtd.org> #<marker (moves after insertion) at 162969 in newgtd.org> #<marker (moves after insertion) at 163731 in newgtd.org> #<marker (moves after insertion) at 162235 in newgtd.org> #<marker (moves after insertion) at 399624 in notes.org> #<marker (moves after insertion) at 165481 in newgtd.org> #<marker (moves after insertion) at 165058 in newgtd.org> #<marker (moves after insertion) at 164459 in newgtd.org> #<marker (moves after insertion) at 57564 in newgtd.org> #<marker (moves after insertion) at 161814 in newgtd.org> #<marker (moves after insertion) at 29221 in idea.org> #<marker (moves after insertion) at 398942 in notes.org> #<marker (moves after insertion) at 108748 in newgtd.org> #<marker (moves after insertion) at 158915 in newgtd.org> #<marker (moves after insertion) at 398482 in notes.org> #<marker (moves after insertion) at 155868 in newgtd.org> #<marker (moves after insertion) at 147108 in newgtd.org>) 0 43)
org-mru-clock-select-workaround-history()
(let* ((org-clock-history (org-mru-clock-select-workaround-history)) (m (org-clock-select-task "Select recent task: "))) (if m (progn (switch-to-buffer (marker-buffer m)) (goto-char (marker-position m)) (org-up-element) (org-show-subtree))))
org-mru-clock-select-recent-task(nil)
funcall-interactively(_org-mru-clock-select-recent-task nil)_
#<subr call-interactively>(org-mru-clock-select-recent-task nil nil)
apply(#<subr call-interactively> org-mru-clock-select-recent-task (nil nil))
call-interactively@ido-cr+-record-current-command(#<subr call-interactively> org-mru-clock-select-recent-task nil nil)
apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (org-mru-clock-select-recent-task nil nil))
call-interactively(org-mru-clock-select-recent-task nil nil)
command-execute(org-mru-clock-select-recent-task)

**Comment by unhammer** [comment]
Thanks! Didn't know cl-subseq errored on shorter lists, switched to seq-take now
