### ISSUE TITLE
FR: when (point) on an org-heading, have it be the first entry to clock into

### ISSUE THREAD

**Issue by bennyandresen** [unhammer/org-mru-clock#3]
even if it doesn't yet have a clock entry.
(Also have the same work in the agenda.)

That seems like a regular use case if you try to be more granular with your clock.

I prefer commands that DWIM. Unfortunately DWIM is very much a personal thing. :-)

**Comment by unhammer** [comment]
I like it! We can make a defcustom to turn it off in case there are people to whom DWIM means something else :) 

Feel free to make a pull request on this, otherwise I'll probably take a stab at it later (a bit busy right now with other projects)
