### ISSUE TITLE
Insert last captured entry too?

### ISSUE THREAD

**Issue by unhammer** [unhammer/org-mru-clock#6]
If you do `org-capture` and file it, then there's a chance it's a task you'll work on soon.

**Comment by stites** [comment]
One datapoint: I'm working with the http://doc.norang.ca/org-mode.html workflow where captured items get a clock added to them (unless there it takes <1m to capture, but this can be changed). So it seems like mru-clock currently has a way to capture these.

Given how long this ticket has been open, and the fact that an emacs noob like myself has a compatible workflow, I think this can be closed until someone else chimes in.

**Comment by unhammer** [comment]
Yeah, since org-capture already provides a mechanism for clocking in to captures, we could say it's already solved in org-mode.

I'll close but keep an open mind about reopening if people have other arguments :)
