### ISSUE TITLE
Allow to capture and clock in simultaneously

### ISSUE THREAD

**Issue by whirm** [unhammer/org-mru-clock#8]
Often I want to clock into a task which I'm not sure I've already created, that means I have to first attempt to clock in, and if it's not there then I have to cancel and capture the new task.

It would be great to be able to be able use the non-matching search as input to a pre-set capture template.

**Comment by unhammer** [comment]
That's a great idea! Should it require any sort of confirmation beyond just `RET`?

I don't know when I'll have time to do this, so in the meanwhile, PR's welcome ;)

… related: https://github.com/unhammer/org-mru-clock/commit/8c27e8667b30d50ddb3ded72cc8087fd79c15e5d – I capture in various ways, so for me at least it'd be useful with something like `(("^foo .*" . "f") (".*" . "t"))` to capture anything matching `^foo ` with the `f` template and anything else with the `t` template.

**Comment by whirm** [comment]
I mostly use two capture templates: A pretty standard one and another that is exactly the same but clocks the new task in. 

With this feature I'd be able to use a single one :)

Thanks!

**Comment by unhammer** [comment]
Hm, would anyone ever want to not clock into a task newly captured with org-mru-clock-in?

**Comment by whirm** [comment]
Wouldn't you just use the regular org-capture flow?

EDIT: Oh, and thanks a lot for working on that!

**Comment by unhammer** [comment]
> Wouldn't you just use the regular org-capture flow?

Probably, that makes it easy :) 

I just pushed a change, if you want to try it's in https://github.com/unhammer/org-mru-clock/compare/on-the-fly-create

**Comment by whirm** [comment]
Will report back ASAP

**Comment by whirm** [comment]
I'm getting this backtrace when pressing RET after typing in some random input:

```lisp
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  (org-mru-clock--clock-in nil nil)
  (org-mru-clock--read "Recent clocks: " (("Fix org mode.....
  (org-mru-clock-in nil)
  (funcall-interactively org-mru-clock-in nil)
  (call-interactively org-mru-clock-in record nil)
  (command-execute org-mru-clock-in record)
  (helm-M-x nil "org-mru-clock-in")
  (funcall-interactively helm-M-x nil "org-mru-clock-in")
```

My config is:

```lisp
(use-package org-mru-clock
      :after org
      :init

      (spacemacs/set-leader-keys "aoi" 'org-mru-clock-in)
      (spacemacs/set-leader-keys "aoI" 'org-mru-clock-select-recent-task)

      (setq org-mru-clock-how-many 20
            org-mru-clock-capture-if-no-match '(;;("^[0-9]+ " . "a")
                                                       (".*" . "T"))
            ;; org-mru-clock-completing-read #'helm-comp-read
            ;; org-mru-clock-keep-formatting t
            ))
```

I've tried with and without setting the completting read function just in case.

**Comment by unhammer** [comment]
Ouch. Try newest git. I've got to stop assuming everyone uses ivy :)

**Comment by whirm** [comment]
Now it works fine unless the capture template sets `:immediate-finish t`

**Comment by unhammer** [comment]
Hmm, I've never used immediate-finish, I'll have a look later. And thanks for helping me test and catch these bugs :-)

**Comment by whirm** [comment]
I mean, it's you doing the hard work :D

**Comment by unhammer** [comment]
git pull and try again?

**Comment by whirm** [comment]
Works now!

Thanks a lot!

**Comment by whirm** [comment]
I'm afraid something must have been lost during the merge to master.

I'm getting the following error again:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  (looking-at nil)
  (org-get-todo-state)
  (org-entry-is-todo-p)
  (org-mru-clock--predicate #<marker at 7838 in packages.el>)
  (#f(compiled-function (m) #<bytecode 0x158b38831715>) #<marker at 7838 in packages.el>)

```

**Comment by unhammer** [comment]
Wops, had set `org-mru-clock-predicate` to `org-entry-is-todo-p` instead of the default `nil` – pushed an update. But even so, that shouldn't have lead to an error. It's a strange error, I can't reproduce it myself. Was it with before you'd gotten a chance to type anything at all?

(It seems from the traceback that the marker was in `packages.el`, I don't understand why that would be returned from `org-mru-clock-files`, though that would explain why `org-get-todo-state` would fail …)

**Comment by whirm** [comment]
0.4.1 is working fine now!

re. `packages.el`: that was the buffer I was editing when I called `org-mru-clock-in` if it's of any use.

Thanks again! I use this feature a dozen times a day now.

**Comment by unhammer** [comment]
No problem :)

(I haven't been able to reproduce the error, but I'll keep an eye out for it.)
